version: '3'

services:
  app:
    build: ./sample-app
    environment:
      DB_HOST: db
      DB_USER: dbuser
      DB_PASSWORD: dbpass
      DB_DATABASE: sample
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      APP_BASE_URL: http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - ./sample-app:/app

  db:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
      MARIADB_DATABASE: sample
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
